# build environment
FROM node:16.18-alpine3.16 as builder

WORKDIR /builder

COPY . .
# COPY public public
# COPY src src
# COPY package.json .
# COPY yarn.lock .

ENV PATH /builder/node_modules/.bin:$PATH

# RUN #yarn add global react-scripts

RUN yarn --production

RUN yarn build


# production environment
FROM nginx:alpine as production

ENV NODE_ENV production

WORKDIR /app

COPY --from=builder /builder/build /app/build

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
